[personal]
name = "Bartosz Słapa"
location = "Warsaw, Mazowieckie, Poland"
github = "https://github.com/suap-dev"
linkedin = "https://www.linkedin.com/in/bartosz-slapa"
email = "bartosz.p.slapa@gmail.com"
phone = "+48505707827"

[experience]
[[experience.job]]
company = "VARSAV Game Studios S.A."
position = "Unreal Engine / Game Programmer"
location = "Warsaw, Poland"
start_date = "February 2024"
end_date = "Present"
responsibilities = [
    "Developed gameplay mechanics for 'Barkour,' a game featuring a four-legged protagonist",
    "Collaborated with artists, designers, and other programmers to ensure smooth integration of assets and features",
    "Optimized performance, profiled the game, and identified areas for improvement in speed and stability",
]

[[experience.job]]
company = "Grip Digital"
position = "Game Developer (C++/Unreal Engine)"
location = "Prague, Czechia"
start_date = "July 2022"
end_date = "October 2022"
responsibilities = [
    "Created mini-games using Unreal Engine 4 and UE_Blueprint",
    "Collaborated with cross-functional teams to develop captivating gameplay experiences",
]

[[experience.job]]
company = "Gamefam"
position = "Game Developer (Roblox/Luau)"
location = "Los Angeles, CA"
start_date = "December 2021"
end_date = "June 2022"
responsibilities = [
    "Programmed new systems, interfaces, and game mechanics in Roblox Studio using Luau",
    "Developed scripted events and improved gameplay based on design specifications",
]

[skills]
languages = ["Rust", "C++", "Lua", "Java", "Python"]
technologies = ["Unreal Engine", "Iced GUI", "Roblox Studio", "Android/Java"]
development = ["Multithreading", "Game Development", "Performance Optimization"]

[education]
[[education.institution]]
name = "Adam Mickiewicz University in Poznań"
course = "Bachelor's Course, Mathematics"
years_attended = "2019 - 2021"

[[education.institution]]
name = "Warsaw University of Technology"
course = "Bachelor's Course, Applied Computer Science"
years_attended = "2008 - 2011"

[certifications]
certs = ["Arc Certified Remote Developer", "Artificial Intelligence (EPICODE)"]
