[personal]
name = "Bartosz Słapa"
location = "Warsaw, Poland"
github = "https://github.com/suap-dev"
linkedin = "https://www.linkedin.com/in/bartosz-slapa"
email = "bartosz.p.slapa@gmail.com"
phone = "+48 505-707-827"

[experience]
[[experience.job]]
company = "VARSAV Game Studios S.A."
position = "Gameplay Programmer"
tech_stack = "Unreal Engine 5, C++, Blueprint, Perforce Helix, Redmine"
start_date = "February 2024"
end_date = "Present"
responsibilities = [
    "Developed gameplay mechanics for 'Barkour', a game featuring a four-legged protagonist.",
    "Collaborated with artists, designers, and other programmers to integrate assets and features.",
    "Profiled the project to identify and implement improvements in speed and stability.",
]

[[experience.job]]
company = "Grip Digital"
position = "Gameplay Programmer"
tech_stack = "Unreal Engine 4, C++, Blueprint, Perforce Helix"
start_date = "July 2022"
end_date = "October 2022"
responsibilities = ["Created mini-games for an unannounced project."]

[[experience.job]]
company = "Gamefam"
position = "Gameplay Programmer"
tech_stack = "Roblox Studio, Lua, Git"
start_date = "December 2021"
end_date = "June 2022"
responsibilities = [
    "Programmed new systems, interfaces, and game mechanics.",
    "Analyzed and iterated on gameplay balance.",
]

[[experience.job]]
company = "Future Mind"
position = "Mobile Application Programmer"
tech_stack = "Android Studio, Java, SQLite, Jira"
start_date = "July 2014"
end_date = "July 2015"
responsibilities = [
    "Created (from mockup to release) a dictionary app, Synonimy.pl.",
    "Supported the development team of the Envelo project for Polish Post by testing and managing bugs.",
]

[[experience.job]]
company = "Self Employed"
position = "Mathematics and Computer Science Tutor"
start_date = "July 2014"
end_date = "June 2024"
responsibilities = [
    "Advanced mathematics and computer science, focusing on algorithms, data structures, and graphics.",
]

[[experience.job]]
company = "Sofrecom"
position = "Business Consultant"
start_date = "February 2011"
end_date = "May 2012"
responsibilities = [
    "Led a project to implement customer satisfaction standards in public administration offices in Poland.",
    "Responsible for humanizing and simplifying administrative language to improve client communication.",
]

[[experience.job]]
company = "Kreatywny Cukier"
position = "Artistic Cake Workshop Manager"
start_date = "January 2010"
end_date = "January 2011"
responsibilities = [
    "Managed projects and team, ensuring timely delivery of artistic cakes under tight deadlines.",
]

[skills]
languages = ["Rust", "C++", "Java", "Lua", "Python", "UE Blueprint", "SQL"]
technologies = [
    "Unreal Engine",
    "Iced GUI",
    "OpenGL/Glium",
    "Nalgebra",
    "Roblox Studio",
    "Android Studio",
]
workflow_tools = ["Perforce Helix", "Git", "Jira", "Redmine"]
human_languages = [
    "Polish (native)",
    "English (fluent)",
    "French (basic)",
    "Hindi (very basic)",
]
soft_skills = [
    "Team Leadership",
    "Client Communication",
    "Problem-solving",
    "Adaptability",
]

[education]
[[education.institution]]
name = "Warsaw University of Technology"
course = "Computer Science"
years_attended = "2008 – 2011"

[[education.institution]]
name = "Adam Mickiewicz University in Poznań"
course = "Mathematics"
years_attended = "2019 – 2021"
